Updated the readme file for BeSIP with initial set of data
Be-Secure/BeSIP pull request #3
Opened 2021-10-28 06:50 UTC by jobyko

2021-10-28 06:51 UTC, jobyko commented
@asa1997 
Please have  a look
Reference : https://github.com/Be-Secure/BeSIP/wiki

2021-11-23 05:00 UTC, asa1997 approved these changes
@jobyko LGTM.
Please do add the rest of the details from the wiki if necessary.

2021-11-25 02:30 UTC, jobyko commented
@panickervinod 
Please merge the PR

2021-11-25 04:40 UTC, panickervinod commented on README.md
> +
@jobyko  @asa1997  Please go through how the EIP repos has been model ..https://github.com/ethereum/EIPs

Update the readme likewise for BESIP

2021-11-25 04:42 UTC, panickervinod commented on README.md
> +This repository holding multiple proposals to integrate code scanning tools in Be-Secure platform. Current set of tools include,
Need not mention the tools here. What needs to go in is information about what is BeSIP ,How is it organized , what should one do to go over , contribute the BeSIP etc.

2021-11-25 04:42 UTC, panickervinod requested changes
@jobyko @asa1997 Please incorporate the feedback in the next pull request.

2021-11-25 04:42 UTC, closed without merging